#!/bin/bash -e

usage() {
    echo "Usage: shdel [-h] PID"
    echo ""
    echo "Kill active job identified by a PID."
    echo ""
    echo "Opts:"
    echo " -h      : display this message"
    exit 1
}

# Option parser
while getopts h OPT
do
    case $OPT in
        (h)
            usage
            ;;
    esac
done

# Remove parsed args
N=1
while [[ $N < $OPTIND ]]
do
    shift
    let N+=1
done

# Check for required args
if [[ $# == 0 ]]
then
    echo Missing arguments ...
    usage
fi

KILL_PID=$1

# Job states are stored in DIR folder
# The PIDs are stored in *.id files
# The exit codes are stored in *.dat files
DIR=/tmp/$USER/shpool
# PID file pattern - do not expand * here
PATTERN=$DIR'/*.id'

if [ ! -d $DIR ]
then
    mkdir -p $DIR
fi

# Loop over PID files. Do not put PATTERN inside quotes so that * is expanded
for ID in $PATTERN
do
    # If no *.id files are found the ID is equal to PATTERN
    if [ "$ID" == "$PATTERN" ]
    then
        echo "Job $PID not found."
        exit 1
    fi

    # Get the process pid and check that it is present in system proc table
    PID=$(cat $ID)
    if [[ $PID == $KILL_PID ]]
    then
        kill $KILL_PID
        sleep 1
        # If still running send KILL signal
        if [ -d /proc/$PID ]
        then
            kill -9 $KILL_PID
        fi
        exit 0
    fi
done

echo "Job $PID not found."
exit 1
