#!/bin/bash -e

usage() {
    echo "Usage: shsub [-h]"
    echo ""
    echo "Check the state of submitted jobs. Outputs one job per line."
    echo "PID STATE"
    echo "PID   : job process ID"
    echo "STATE:"
    echo " -1 : job is running"
    echo " -2 : job exit code is missing"
    echo " N  : job has finished with exit code N"
    echo ""
    echo "Opts:"
    echo " -h      : display this message"
    exit 1
}

# Option parser
while getopts h OPT
do
    case $OPT in
        (h)
            usage
            ;;
    esac
done

# Remove parsed args
N=1
while [[ $N < $OPTIND ]]
do
    shift
    let N+=1
done

# Job states are stored in DIR folder
# The PIDs are stored in *.id files
# The exit codes are stored in *.dat files
DIR=/tmp/$USER/shpool
# PID file pattern - do not expand * here
PATTERN=$DIR'/*.dat'

if [ ! -d $DIR ]
then
    mkdir -p $DIR
fi

# Print running processes
ps -u $USER -o pid | grep -v PID | awk '{print $1" -1"}'

# Print finished processes
cat $PATTERN

# Remove info about processes finished more than an hour ago
find $DIR -name "*.dat" -type f -mmin +60 | sed 's/\.dat/\.id/' | xargs rm -f
find $DIR -name "*.dat" -type f -mmin +60 -delete

exit 0
